// src/themes/vue/static/src/pages/Host/HostModal.vue

<!-- Copyright IBM Corp, All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
-->
<template>
  <Modal
    v-model="visible"
    :title="title"
    ok-text="OK"
    cancel-text="Cancel">
    <Form ref="hostForm" :model="formItem" :rules="ruleValidate" :label-width="80">
      <FormItem label="Host Name" prop="name" :label-width="100">
        <Input type="text" :readonly="type === 'update'" v-model="formItem.name" placeholder="Input host name" />
      </FormItem>
      <FormItem prop="worker_api" :label-width="100">
        <label slot="label">
          URL
          <Tooltip placement="top-end">
            <Icon type="help-circled" />
            <div slot="content">
              <p>Input the node ip and port</p>
              <p>example: 192.168.1.1:6527</p>
            </div>
          </Tooltip>
        </label>
        <Input :readonly="type === 'update'" v-model="formItem.worker_api">
          <span slot="prepend">tcp://</span>
        </Input>
      </FormItem>
      <FormItem label="Capacity" :label-width="100">
        <InputNumber :min="1" v-model="formItem.capacity"></InputNumber>
      </FormItem>
      <FormItem label="Log Level" prop="log_level" :label-width="100">
        <Select v-model="formItem.log_level" placeholder="Select log level">
          <Option value="DEBUG">DEBUG</Option>
          <Option value="INFO">INFO</Option>
          <Option value="NOTICE">NOTICE</Option>
          <Option value="WARNING">WARNING</Option>
          <Option value="ERROR">ERROR</Option>
          <Option value="CRITICAL">CRITICAL</Option>
        </Select>
      </FormItem>
      <FormItem label="Log Type" prop="log_type" :label-width="100">
        <Select v-model="formItem.log_type" placeholder="Select log type">
          <Option value="local">LOCAL</Option>
          <Option value="syslog">SYSLOG</Option>
        </Select>
      </FormItem>
      <FormItem v-if="formItem.log_type === 'syslog'" label="Log Server" :label-width="100">
        <Input v-model="formItem.log_server" />
      </FormItem>
      <FormItem :label-width="100">
        <label slot="label">
          Schedulable
          <Tooltip placement="top-end">
            <Icon type="help-circled" />
            <div slot="content">
              Schedulable for cluster request
            </div>
          </Tooltip>
        </label>
        <i-switch v-model="formItem.schedulable" size="large">
          <span v-for="item in switchChoices" :slot="item.value">{{ item.label }}</span>
        </i-switch>
      </FormItem>
      <FormItem :label-width="100">
        <label slot="label">
          Keep filed
          <Tooltip placement="top-end">
            <Icon type="help-circled" />
            <div slot="content">
              Keep filled with cluster
            </div>
          </Tooltip>
        </label>
        <i-switch v-model="formItem.autofill" size="large">
          <span v-for="item in switchChoices" :slot="item.value">{{ item.label }}</span>
        </i-switch>
      </FormItem>
    </Form>
    <div slot="footer">
      <Button type="text" @click="hideModal">Cancel</Button>
      <Button type="primary" :loading="submitting" @click="submitForm">Ok</Button>
    </div>
    </Modal>
</template>

<script>
  import { mapActions } from 'vuex'
  export default {
    props: ['type', 'visible', 'onCancel', 'formItem', 'onOk', 'host'],
    data () {
      const validateName = (rule, value, callback) => {
        callback()
      }
      return {
        ruleValidate: {
          name: [
            { required: true, message: 'Please input Host name', trigger: 'blur' },
            { validator: validateName, trigger: 'blur' }
          ],
          worker_api: [
            { required: true, message: 'Please input URL', trigger: 'blur' }
          ],
          log_level: [
            { required: true, message: 'Please Select a log level', trigger: 'blur' }
          ],
          log_type: [
            { required: true, message: 'Please Select a log type', trigger: 'blur' }
          ]
        },
        switchChoices: [
          {
            value: true,
            label: 'Yes'
          },
          {
            value: false,
            label: 'No'
          }
        ]
      }
    },
    computed: {
      title () {
        if (this.type === 'create') {
          return 'Create Host'
        } else {
          return 'Edit Host'
        }
      }
    },
    methods: {
      ...mapActions([
        'updateHost',
        'createHost'
      ]),
      hideModal () {
        this.$refs['hostForm'].resetFields()
        this.onCancel()
      },
      submitForm () {
        this.$refs['hostForm'].validate((valid) => {
          this.submitting = true
          if (valid) {
            this.formItem.schedulable = this.formItem.schedulable ? 'true' : 'false'
            this.formItem.autofill = this.formItem.autofill ? 'true' : 'false'
            if (this.type === 'create') {
              this.createHost(this.formItem)
              this.submitting = false
              this.onCancel()
            } else if (this.type === 'update') {
              this.formItem.id = this.host.id
              this.updateHost(this.formItem)
              this.submitting = false
              this.onCancel()
            }
          } else {
            this.submitting = false
          }
        })
      }
    }
  }
</script>

<style>
</style>

// src/themes/react/static/js/routes/host/HostModal.js

/* Copyright IBM Corp, All Rights Reserved.

 SPDX-License-Identifier: Apache-2.0
 */

/**
 * Created by yuehaitao on 2017/2/9.
 */
import React, { PropTypes } from 'react'
import { Form, Input, InputNumber, Radio, Modal, Tooltip, Icon, Select, Switch } from 'antd'
import validator from 'validator'
const FormItem = Form.Item
const Option = Select.Option

class HostModal extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            posting: false,
            logType: 'local'
        }
        this.handleOk = this.handleOk.bind(this)
        this.logTypeChange = this.logTypeChange.bind(this)
    }
    logTypeChange(value) {
        this.setState({
            logType: value
        })
    }
    handleOk() {
        const {
            onOk,
            form: {
                validateFields,
                getFieldsValue,
                setFields
            },
            item,
            type
        } = this.props
        validateFields((errors) => {
            if (errors) {
                return
            }
            let data = getFieldsValue()
            const url = data.worker_api
            if (url.split(":").length !== 2) {
                setFields({
                    url: {
                        value: url,
                        errors: [new Error('Must input ip:port')]
                    }
                })
                return
            }
            const ip = url.split(":")[0]
            const port = parseInt(url.split(":")[1])
            if (!validator.isIP(ip)) {
                setFields({
                    url: {
                        value: url,
                        errors: [new Error('Must input valid ip address')]
                    }
                })
                return
            }
            if (port<0 || port>65535) {
                setFields({
                    url: {
                        value: url,
                        errors: [new Error('Must input valid port')]
                    }
                })
                return
            }
            this.setState({
                posting: true
            });
            if (!('log_server' in data)) {
                data.log_server = '';
            }
            if (type !== 'create') {
                data.id = item.id
            }
            onOk(data)
        })
}
    render() {
        const {
            visible,
            item = {},
            onCancel,
            type,
            form: {
                getFieldDecorator,
            },
        } = this.props
        const {posting, logType} = this.state
        let title = "Add Host"
        if (type === 'update') {
            title = "Update Host"
        }
        const modalOpts = {
            title: title,
            visible,
            onOk: this.handleOk,
            onCancel,
            confirmLoading: posting,
            okText: 'Confirm',
            cancelText: 'Cancel',
            wrapClassName: 'vertical-center-modal',
        }
        const formItemLayout = {
            labelCol: {
                span: 6,
            },
            wrapperCol: {
                span: 14,
            },
        }

        return (
            <Modal {...modalOpts}>
                <Form layout="horizontal">
                    <FormItem label="Name" hasFeedback {...formItemLayout}>
                        {getFieldDecorator('name', {
                            initialValue: item.name,
                            rules: [
                                {
                                    required: true,
                                    message: 'Must input Host name',
                                },
                            ],
                        })(<Input />)}
                    </FormItem>
                    <FormItem label={<span>URL&nbsp;
                        <Tooltip title="Input the node ip and port, example: 192.168.1.1:6527">
                        <Icon type="question-circle-o" />
                    </Tooltip>
                </span>} hasFeedback {...formItemLayout}>
                        {getFieldDecorator('worker_api', {
                            initialValue: type === "create" ? "" : item.worker_api.split("//")[1],
                            rules: [
                                {
                                    required: true,
                                    message: 'Must input Host url',
                                },
                            ],
                        })(<Input addonBefore="tcp://" />)}
                    </FormItem>
                    <FormItem label="Capacity" hasFeedback {...formItemLayout}>
                        {getFieldDecorator('capacity', {
                            initialValue: type === "create" ? 1 : item.capacity,
                            rules: [
                                {
                                    required: true,
                                    message: 'Must input capacity',
                                },
                            ],
                        })(<InputNumber min={1} />)}
                    </FormItem>
                    <FormItem label="Log Level" hasFeedback {...formItemLayout}>
                        {getFieldDecorator('log_level', {
                            initialValue: type === "create" ? "DEBUG" : item.log_level,
                            rules: [
                                {
                                    required: true,
                                    message: 'Must Select Log level',
                                },
                            ],
                        })(<Select>
                            <Option value="DEBUG">DEBUG</Option>
                            <Option value="INFO">INFO</Option>
                            <Option value="NOTICE">NOTICE</Option>
                            <Option value="WARNING">WARNING</Option>
                            <Option value="ERROR">ERROR</Option>
                            <Option value="CRITICAL">CRITICAL</Option>
                        </Select>)}
                    </FormItem>
                    <FormItem label="Log Type" hasFeedback {...formItemLayout}>
                        {getFieldDecorator('log_type', {
                            initialValue: type === "create" ? "local" : item.log_type,
                            rules: [
                                {
                                    required: true,
                                    message: 'Must Select Log type',
                                },
                            ],
                        })(<Select onChange={this.logTypeChange}>
                            <Option value="local">LOCAL</Option>
                            <Option value="syslog">SYSLOG</Option>
                        </Select>)}
                    </FormItem>
                    {logType === 'syslog' &&
                    <FormItem label="Log Server" hasFeedback {...formItemLayout}>
                        {getFieldDecorator('log_server', {
                            initialValue: type === 'create' ? '' : item.log_server,
                            rules: [
                                {
                                    required: logType === 'syslog',
                                    message: 'Must input Log Server',
                                },
                            ],
                        })(<Input />)}
                    </FormItem>
                    }
                    <FormItem label={<span>Schedulable&nbsp;
                        <Tooltip title="Schedulable for cluster request">
                        <Icon type="question-circle-o" />
                    </Tooltip>
                </span>} hasFeedback {...formItemLayout}>
                        {getFieldDecorator('schedulable', {
                            initialValue: type === 'create' ? false : item.schedulable === "true",
                            valuePropName: 'checked'
                        })(<Switch />)}
                    </FormItem>
                    <FormItem label={<span>Keep filled&nbsp;
                        <Tooltip title="Keep filled with cluster">
                        <Icon type="question-circle-o" />
                    </Tooltip>
                </span>} hasFeedback {...formItemLayout}>
                        {getFieldDecorator('autofill', {
                            initialValue: type === 'create' ? false : item.autofill === "true",
                            valuePropName: 'checked'
                        })(<Switch />)}
                    </FormItem>
                </Form>
            </Modal>
        )
    }
}

HostModal.propTypes = {
    visible: PropTypes.any,
    form: PropTypes.object,
    item: PropTypes.object,
    onOk: PropTypes.func,
    onCancel: PropTypes.func,
    type: PropTypes.any
}

export default Form.create()(HostModal)
